// Generated register defines for PINMUX

// Copyright information found in source file:
// Copyright lowRISC contributors.Copyright lowRISC contributors.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef _PINMUX_REG_DEFS_
#define _PINMUX_REG_DEFS_

// Register write enable for all control registers.
#define PINMUX_REGEN(id) (PINMUX##id##_BASE_ADDR + 0x0)
#define PINMUX_REGEN_REG_OFFSET 0x0
#define PINMUX_REGEN_WEN 0

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL0(id) (PINMUX##id##_BASE_ADDR + 0x4)
#define PINMUX_PERIPH_INSEL0_REG_OFFSET 0x4
#define PINMUX_PERIPH_INSEL0_IN0_MASK 0x3f
#define PINMUX_PERIPH_INSEL0_IN0_OFFSET 0
#define PINMUX_PERIPH_INSEL0_IN1_MASK 0x3f
#define PINMUX_PERIPH_INSEL0_IN1_OFFSET 6
#define PINMUX_PERIPH_INSEL0_IN2_MASK 0x3f
#define PINMUX_PERIPH_INSEL0_IN2_OFFSET 12
#define PINMUX_PERIPH_INSEL0_IN3_MASK 0x3f
#define PINMUX_PERIPH_INSEL0_IN3_OFFSET 18
#define PINMUX_PERIPH_INSEL0_IN4_MASK 0x3f
#define PINMUX_PERIPH_INSEL0_IN4_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL1(id) (PINMUX##id##_BASE_ADDR + 0x8)
#define PINMUX_PERIPH_INSEL1_REG_OFFSET 0x8
#define PINMUX_PERIPH_INSEL1_IN5_MASK 0x3f
#define PINMUX_PERIPH_INSEL1_IN5_OFFSET 0
#define PINMUX_PERIPH_INSEL1_IN6_MASK 0x3f
#define PINMUX_PERIPH_INSEL1_IN6_OFFSET 6
#define PINMUX_PERIPH_INSEL1_IN7_MASK 0x3f
#define PINMUX_PERIPH_INSEL1_IN7_OFFSET 12
#define PINMUX_PERIPH_INSEL1_IN8_MASK 0x3f
#define PINMUX_PERIPH_INSEL1_IN8_OFFSET 18
#define PINMUX_PERIPH_INSEL1_IN9_MASK 0x3f
#define PINMUX_PERIPH_INSEL1_IN9_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL2(id) (PINMUX##id##_BASE_ADDR + 0xc)
#define PINMUX_PERIPH_INSEL2_REG_OFFSET 0xc
#define PINMUX_PERIPH_INSEL2_IN10_MASK 0x3f
#define PINMUX_PERIPH_INSEL2_IN10_OFFSET 0
#define PINMUX_PERIPH_INSEL2_IN11_MASK 0x3f
#define PINMUX_PERIPH_INSEL2_IN11_OFFSET 6
#define PINMUX_PERIPH_INSEL2_IN12_MASK 0x3f
#define PINMUX_PERIPH_INSEL2_IN12_OFFSET 12
#define PINMUX_PERIPH_INSEL2_IN13_MASK 0x3f
#define PINMUX_PERIPH_INSEL2_IN13_OFFSET 18
#define PINMUX_PERIPH_INSEL2_IN14_MASK 0x3f
#define PINMUX_PERIPH_INSEL2_IN14_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL3(id) (PINMUX##id##_BASE_ADDR + 0x10)
#define PINMUX_PERIPH_INSEL3_REG_OFFSET 0x10
#define PINMUX_PERIPH_INSEL3_IN15_MASK 0x3f
#define PINMUX_PERIPH_INSEL3_IN15_OFFSET 0
#define PINMUX_PERIPH_INSEL3_IN16_MASK 0x3f
#define PINMUX_PERIPH_INSEL3_IN16_OFFSET 6
#define PINMUX_PERIPH_INSEL3_IN17_MASK 0x3f
#define PINMUX_PERIPH_INSEL3_IN17_OFFSET 12
#define PINMUX_PERIPH_INSEL3_IN18_MASK 0x3f
#define PINMUX_PERIPH_INSEL3_IN18_OFFSET 18
#define PINMUX_PERIPH_INSEL3_IN19_MASK 0x3f
#define PINMUX_PERIPH_INSEL3_IN19_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL4(id) (PINMUX##id##_BASE_ADDR + 0x14)
#define PINMUX_PERIPH_INSEL4_REG_OFFSET 0x14
#define PINMUX_PERIPH_INSEL4_IN20_MASK 0x3f
#define PINMUX_PERIPH_INSEL4_IN20_OFFSET 0
#define PINMUX_PERIPH_INSEL4_IN21_MASK 0x3f
#define PINMUX_PERIPH_INSEL4_IN21_OFFSET 6
#define PINMUX_PERIPH_INSEL4_IN22_MASK 0x3f
#define PINMUX_PERIPH_INSEL4_IN22_OFFSET 12
#define PINMUX_PERIPH_INSEL4_IN23_MASK 0x3f
#define PINMUX_PERIPH_INSEL4_IN23_OFFSET 18
#define PINMUX_PERIPH_INSEL4_IN24_MASK 0x3f
#define PINMUX_PERIPH_INSEL4_IN24_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL5(id) (PINMUX##id##_BASE_ADDR + 0x18)
#define PINMUX_PERIPH_INSEL5_REG_OFFSET 0x18
#define PINMUX_PERIPH_INSEL5_IN25_MASK 0x3f
#define PINMUX_PERIPH_INSEL5_IN25_OFFSET 0
#define PINMUX_PERIPH_INSEL5_IN26_MASK 0x3f
#define PINMUX_PERIPH_INSEL5_IN26_OFFSET 6
#define PINMUX_PERIPH_INSEL5_IN27_MASK 0x3f
#define PINMUX_PERIPH_INSEL5_IN27_OFFSET 12
#define PINMUX_PERIPH_INSEL5_IN28_MASK 0x3f
#define PINMUX_PERIPH_INSEL5_IN28_OFFSET 18
#define PINMUX_PERIPH_INSEL5_IN29_MASK 0x3f
#define PINMUX_PERIPH_INSEL5_IN29_OFFSET 24

// Mux select for peripheral inputs.
#define PINMUX_PERIPH_INSEL6(id) (PINMUX##id##_BASE_ADDR + 0x1c)
#define PINMUX_PERIPH_INSEL6_REG_OFFSET 0x1c
#define PINMUX_PERIPH_INSEL6_IN30_MASK 0x3f
#define PINMUX_PERIPH_INSEL6_IN30_OFFSET 0
#define PINMUX_PERIPH_INSEL6_IN31_MASK 0x3f
#define PINMUX_PERIPH_INSEL6_IN31_OFFSET 6

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL0(id) (PINMUX##id##_BASE_ADDR + 0x20)
#define PINMUX_MIO_OUTSEL0_REG_OFFSET 0x20
#define PINMUX_MIO_OUTSEL0_OUT0_MASK 0x3f
#define PINMUX_MIO_OUTSEL0_OUT0_OFFSET 0
#define PINMUX_MIO_OUTSEL0_OUT1_MASK 0x3f
#define PINMUX_MIO_OUTSEL0_OUT1_OFFSET 6
#define PINMUX_MIO_OUTSEL0_OUT2_MASK 0x3f
#define PINMUX_MIO_OUTSEL0_OUT2_OFFSET 12
#define PINMUX_MIO_OUTSEL0_OUT3_MASK 0x3f
#define PINMUX_MIO_OUTSEL0_OUT3_OFFSET 18
#define PINMUX_MIO_OUTSEL0_OUT4_MASK 0x3f
#define PINMUX_MIO_OUTSEL0_OUT4_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL1(id) (PINMUX##id##_BASE_ADDR + 0x24)
#define PINMUX_MIO_OUTSEL1_REG_OFFSET 0x24
#define PINMUX_MIO_OUTSEL1_OUT5_MASK 0x3f
#define PINMUX_MIO_OUTSEL1_OUT5_OFFSET 0
#define PINMUX_MIO_OUTSEL1_OUT6_MASK 0x3f
#define PINMUX_MIO_OUTSEL1_OUT6_OFFSET 6
#define PINMUX_MIO_OUTSEL1_OUT7_MASK 0x3f
#define PINMUX_MIO_OUTSEL1_OUT7_OFFSET 12
#define PINMUX_MIO_OUTSEL1_OUT8_MASK 0x3f
#define PINMUX_MIO_OUTSEL1_OUT8_OFFSET 18
#define PINMUX_MIO_OUTSEL1_OUT9_MASK 0x3f
#define PINMUX_MIO_OUTSEL1_OUT9_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL2(id) (PINMUX##id##_BASE_ADDR + 0x28)
#define PINMUX_MIO_OUTSEL2_REG_OFFSET 0x28
#define PINMUX_MIO_OUTSEL2_OUT10_MASK 0x3f
#define PINMUX_MIO_OUTSEL2_OUT10_OFFSET 0
#define PINMUX_MIO_OUTSEL2_OUT11_MASK 0x3f
#define PINMUX_MIO_OUTSEL2_OUT11_OFFSET 6
#define PINMUX_MIO_OUTSEL2_OUT12_MASK 0x3f
#define PINMUX_MIO_OUTSEL2_OUT12_OFFSET 12
#define PINMUX_MIO_OUTSEL2_OUT13_MASK 0x3f
#define PINMUX_MIO_OUTSEL2_OUT13_OFFSET 18
#define PINMUX_MIO_OUTSEL2_OUT14_MASK 0x3f
#define PINMUX_MIO_OUTSEL2_OUT14_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL3(id) (PINMUX##id##_BASE_ADDR + 0x2c)
#define PINMUX_MIO_OUTSEL3_REG_OFFSET 0x2c
#define PINMUX_MIO_OUTSEL3_OUT15_MASK 0x3f
#define PINMUX_MIO_OUTSEL3_OUT15_OFFSET 0
#define PINMUX_MIO_OUTSEL3_OUT16_MASK 0x3f
#define PINMUX_MIO_OUTSEL3_OUT16_OFFSET 6
#define PINMUX_MIO_OUTSEL3_OUT17_MASK 0x3f
#define PINMUX_MIO_OUTSEL3_OUT17_OFFSET 12
#define PINMUX_MIO_OUTSEL3_OUT18_MASK 0x3f
#define PINMUX_MIO_OUTSEL3_OUT18_OFFSET 18
#define PINMUX_MIO_OUTSEL3_OUT19_MASK 0x3f
#define PINMUX_MIO_OUTSEL3_OUT19_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL4(id) (PINMUX##id##_BASE_ADDR + 0x30)
#define PINMUX_MIO_OUTSEL4_REG_OFFSET 0x30
#define PINMUX_MIO_OUTSEL4_OUT20_MASK 0x3f
#define PINMUX_MIO_OUTSEL4_OUT20_OFFSET 0
#define PINMUX_MIO_OUTSEL4_OUT21_MASK 0x3f
#define PINMUX_MIO_OUTSEL4_OUT21_OFFSET 6
#define PINMUX_MIO_OUTSEL4_OUT22_MASK 0x3f
#define PINMUX_MIO_OUTSEL4_OUT22_OFFSET 12
#define PINMUX_MIO_OUTSEL4_OUT23_MASK 0x3f
#define PINMUX_MIO_OUTSEL4_OUT23_OFFSET 18
#define PINMUX_MIO_OUTSEL4_OUT24_MASK 0x3f
#define PINMUX_MIO_OUTSEL4_OUT24_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL5(id) (PINMUX##id##_BASE_ADDR + 0x34)
#define PINMUX_MIO_OUTSEL5_REG_OFFSET 0x34
#define PINMUX_MIO_OUTSEL5_OUT25_MASK 0x3f
#define PINMUX_MIO_OUTSEL5_OUT25_OFFSET 0
#define PINMUX_MIO_OUTSEL5_OUT26_MASK 0x3f
#define PINMUX_MIO_OUTSEL5_OUT26_OFFSET 6
#define PINMUX_MIO_OUTSEL5_OUT27_MASK 0x3f
#define PINMUX_MIO_OUTSEL5_OUT27_OFFSET 12
#define PINMUX_MIO_OUTSEL5_OUT28_MASK 0x3f
#define PINMUX_MIO_OUTSEL5_OUT28_OFFSET 18
#define PINMUX_MIO_OUTSEL5_OUT29_MASK 0x3f
#define PINMUX_MIO_OUTSEL5_OUT29_OFFSET 24

// Mux select for MIO outputs.
#define PINMUX_MIO_OUTSEL6(id) (PINMUX##id##_BASE_ADDR + 0x38)
#define PINMUX_MIO_OUTSEL6_REG_OFFSET 0x38
#define PINMUX_MIO_OUTSEL6_OUT30_MASK 0x3f
#define PINMUX_MIO_OUTSEL6_OUT30_OFFSET 0
#define PINMUX_MIO_OUTSEL6_OUT31_MASK 0x3f
#define PINMUX_MIO_OUTSEL6_OUT31_OFFSET 6

#endif  // _PINMUX_REG_DEFS_
// End generated register defines for PINMUX
